### ISSUE TITLE
v1 release

### ISSUE THREAD

**Issue by Keats** [Keats/tera#331]
v1 should be released after the edition 2018 has been released to ensure everything works properly.
Beta versions can be released before that though in order to get all the changes a bit battle-tested, such as using it in Gutenberg.

Blockers:

- [x] #328 
- [x] #297 
- [x] #322 
- [x] #256 
- [x] #219 (#299 is related)
- [x] #212 (ensure globwalk works well on every OS)
- [x] remove `Context::add` (deprecated for now)
- [x] deprecate  `global_function` for `function`
- [x] remove `global_function` everywhere
- [x] remove `compile_templates!`
- [ ] look into not using serde_json
- [x] #374

Undecided:

- [ ] #320 this is a backward compatible change so no hurry
- [ ] #265 the usecase is pretty narrow, need to see if it the changes to the code to allow that are worth doing
- [x] #308 I would err into "no" because of the potentially weird/unreadable syntax it would allow
- [ ] #340 would be a huge work (I think) I don't have the time for right now

**Comment by Keats** [comment]
If you're reading this and wondering whether you should use the alpha release on crates.io, the answer is no. Wait for the v1 release as there will breaking changes in between alpha releases

**Comment by Keats** [comment]
Looks like it's mostly ready to go but there's still #410, #404, #375 and #368 I'd like to get in though.

None of them are huge time sink. The other issues can be added after 1.0.

Anything else anyone is missing and which would be a breaking change?

**Comment by Keats** [comment]
Anything breaking missing for a v1 release? Otherwise it's going to happen next week.

**Comment by Keats** [comment]
v1 is released!
